# Generated by Django 2.2.5 on 2019-09-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationSlot',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('time_in_minutes', models.PositiveIntegerField(default=0)),
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'irrigation_slots',
                'ordering': ['slot_id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False)),
                ('testing', models.BooleanField(default=False)),
                ('current_slot', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'program_status',
            },
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('name', models.CharField(max_length=10)),
                ('day_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'week_days',
                'ordering': ['day_id'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationHour',
            fields=[
                ('hour', models.TimeField()),
                ('hour_id', models.AutoField(primary_key=True, serialize=False)),
                ('week_days', models.ManyToManyField(to='scheduleManager.WeekDay')),
            ],
            options={
                'db_table': 'irrigation_hours',
                'ordering': ['hour_id'],
            },
        ),
    ]
