# Generated by Django 2.2.5 on 2019-09-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('rain_intensity', models.FloatField()),
            ],
            options={
                'db_table': 'weather_data',
                'ordering': ['datetime'],
            },
        ),
    ]
