# Generated by Django 2.2.5 on 2020-05-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleManager', '0002_weatherdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot1_time', models.PositiveIntegerField(default=60)),
                ('slot2_time', models.PositiveIntegerField(default=60)),
                ('slot3_time', models.PositiveIntegerField(default=60)),
                ('slot4_time', models.PositiveIntegerField(default=60)),
                ('slot5_time', models.PositiveIntegerField(default=60)),
                ('slot6_time', models.PositiveIntegerField(default=60)),
                ('slot1_active', models.BooleanField(default=True)),
                ('slot2_active', models.BooleanField(default=True)),
                ('slot3_active', models.BooleanField(default=True)),
                ('slot4_active', models.BooleanField(default=True)),
                ('slot5_active', models.BooleanField(default=True)),
                ('slot6_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cycle_settings',
            },
        ),
    ]
