# Generated by Django 2.2.5 on 2020-05-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleManager', '0004_auto_20200517_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclesettings',
            name='slot6_active',
            field=models.TextField(default=''),
        ),
    ]
