# Generated by Django 2.2.5 on 2020-05-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleManager', '0005_cyclesettings_slot6_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyclesettings',
            name='slot6_active',
            field=models.BooleanField(default=''),
        ),
    ]
