# Generated by Django 2.2.5 on 2020-05-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleManager', '0006_auto_20200518_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programstatus',
            name='testing',
        ),
        migrations.AddField(
            model_name='programstatus',
            name='manual',
            field=models.BooleanField(default=True),
        ),
    ]
