# Generated by Django 2.2.5 on 2020-05-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleManager', '0007_auto_20200521_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='programstatus',
            name='next_program',
            field=models.TextField(default='Desconegut'),
        ),
    ]
