# Generated by Django 2.2.5 on 2020-05-22 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleManager', '0013_auto_20200522_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programstatus',
            name='next_program_hour',
            field=models.TimeField(default=datetime.datetime(2020, 5, 22, 9, 49, 42, 94796)),
        ),
    ]
