# Generated by Django 2.2.5 on 2020-05-22 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleManager', '0015_remove_programstatus_next_program_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='programstatus',
            name='next_program_hour',
            field=models.TimeField(default=datetime.datetime(2020, 5, 22, 9, 55, 0, 938361)),
        ),
    ]
