# Generated by Django 2.2.5 on 2020-05-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleManager', '0017_auto_20200522_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programstatus',
            name='next_program_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
